---
- include: "tune.yml"
- include: "install.yml"
- include: "facts.yml"
- include: "configure.yml"

- name: Start CockroachDB
  become: yes
  service: name=cockroachdb.service state=started enabled=yes
